# Site settings
title: modimore.github.io
email: quinn.e.mortimer@gmail.com
description: >
  Hi! My name is Quinn and this is my website. Look around for some information about my current projects and skills, or check out my resume.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://modimore.github.io" # the base hostname & protocol for your site
# twitter_username:
github_username: modimore

defaults:
  -
    scope:
      path: "_about"
      type: "about"
    values:
      layout: "page"
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
      priority: 0
  -
    scope:
      path: "_clean"
      type: "clean"
    values:
      layout: "clean"

collections:
  projects:
    output: true
  about:
    output: true
  clean:
    output: false

# Build settings
markdown: kramdown
