# Site settings
title: modimore.github.io
repository: modimore/modimore.github.io
baseurl: ""
url: "https://modimore.github.io"

# Maintainer info
email: quinn.e.mortimer@gmail.com
github_username: modimore

description: >
  Hi! My name is Quinn and this is my website. Look around for some information about my current projects and skills, or check out my resume.

defaults:
  -
    scope:
      path: "_about"
      type: "about"
    values:
      layout: "page"
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
      priority: 0
  -
    scope:
      path: "_print"
      type: "print"
    values:
      layout: "print"

collections:
  projects:
    output: true
  about:
    output: true
  print:
    output: true

# Build settings
markdown: kramdown
